---
title: "MDS-long-term_Ed"
author: "Ed Bonneville"
date: "7-1-2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

#if (suppressWarnings(!require("pacman", character.only = T))) install.packages("pacman", dep = T); library(pacman)

pacman::p_load("MASS", "tidyverse", "mice", "smcfcs",
               "mitools", "survival", "cmprsk", "foreign",
               "naniar", "VIM", "mstate")

set.seed(1984)
```

## Data prep


```{r readin}

# Suppress warnings here
dat_orig <- read.spss("Final_MDS_Longterm_20200106_LK.sav",
                      to.data.frame = T,
                      use.value.labels = T,
                      use.missings = T, 
                      max.value.labels = 8)
               
# attributes(dat_mds)$variable.labels

# Depends on tidyverse
select_keeplabs <- function(.data, ...) {
  
  # Subsetted data
  new_dat <- .data %>% dplyr::select(...)
  
  # Character vector of variables kept
  vars_kept <- names(new_dat)
  
  # Adjust attributes
  attr_obj <- attributes(new_dat)$variable.labels
  var_labs <- attr_obj[names(attr_obj) %in% vars_kept]
  matched_labs <- var_labs[order(match(names(var_labs), vars_kept))]

  attributes(new_dat)$variable.labels <- matched_labs
  
  return(new_dat)
}

#selecto <- function(.data) ...
vars_keep <- c("PATSEX", "age_allo1", "YEAR_allo1",
               "mdsclass", "donorrel", "ric_allo1", "bm_allo1",
               "pb_allo1", "AGEDONOR_allo1_1", "rel_s_allo1",
               "rel_allo1", "ci_s_allo1", "ci_allo1", "srv_s_allo1",
               "srv_allo1")

# Keep variables from study 
dat_mds <- dat_orig %>% 
  select_keeplabs(vars_keep) 
```


# Basic exploration

```{r vis_explor}
gg_miss_var(dat_mds)
```


# Estimate marginal AFT models for both Rel and NRM

```{r aft_rel_nrm}
# Convert indicators
dat_mds <- dat_mds %>% 
  mutate(delta = as.numeric(ci_s_allo1) - 1,
         srv_s_allo1 = as.numeric(srv_s_allo1) - 1)

#dat_mds <- dat_mds %>% filter(mdsclass == "MDS without excess blasts")

# Calculate CumIncs
cumin_rel_nrm <- cuminc(dat_mds$ci_allo1, dat_mds$delta)
plot(cumin_rel_nrm, xlab = "Months", col = c("blue", "black"), curvlab = c("Relapse", "NRM"), xlim = c(0, 120))


# Relapse - divide by 12 to put in years
mod_rel <- survreg(Surv(ci_allo1 / 12, delta == 1) ~ 1, 
                   data = dat_mds, dist = "weibull")

coefs_rel <- mod_rel$coefficients
shape_rel <- 1 / mod_rel$scale
rate_rel <- exp(coefs_rel[1])^(-shape_rel)

# Print it 
cat(paste("For Rel:\n",
          "Shape =", round(shape_rel, 3),
          "\n Rate =", round(rate_rel, 3)))


# NRM
mod_nrm <- survreg(Surv(ci_allo1 / 12, delta == 2) ~ 1, 
                   data = dat_mds, dist = "weibull")

coefs_nrm <- mod_nrm$coefficients
shape_nrm <- 1 / mod_nrm$scale
rate_nrm <- exp(coefs_nrm[1])^(-shape_nrm)

cat(paste("For NRM:\n",
          "Shape =", round(shape_nrm, 3),
          "\n Rate =", round(rate_nrm, 3)))
```


# Estimate censoring distribution

Admin censoring at 60 months.

Check rev KM too

```{r aft_cens}
# Admin cens at 60m
# Censoring is event and people alive after 60 die at 60.01
dat_60mo_cens <- dat_mds %>% 
  mutate(srv_s_60 = ifelse(srv_allo1 > 60, 1, srv_s_allo1), # Ev
         srv_allo1_60 = ifelse(srv_allo1 > 60, 60.01, srv_allo1))

# Run reverse KM
rev_KM <- survfit(Surv(srv_allo1_60, srv_s_60 == 1) ~ 1, data = dat_60mo_cens)
plot(rev_KM)


# Fit weibull AFT (for exponential check, see if shape close to 1)
mod_cens_weib <- survreg(Surv(srv_allo1_60 / 12, srv_s_60 == 0) ~ 1, 
                    data = dat_60mo_cens, dist = "weibull")

coefs_cens <- mod_cens_weib$coefficients
shape_cens_weib <- 1 / mod_cens_weib$scale
rate_cens_weib <- exp(coefs_cens[1])^(-shape_cens)

cat(paste("For censoring:\n",
          "Shape =", round(shape_cens_weib, 3),
          "\n Rate =", round(rate_cens_weib, 3)))


# Fit exponential AFT 
mod_cens <- survreg(Surv(srv_allo1_60 / 12, srv_s_60 == 0) ~ 1, 
                    data = dat_60mo_cens, dist = "exponential")

coefs_cens <- mod_cens$coefficients
rate_cens <- exp(coefs_cens[1])^(-1)

cat(paste("For censoring:\n",
          "Shape =", round(1, 3), "(Exponential)",
          "\n Rate =", round(rate_cens, 3)))
```

# Summarise parameters 

```{r params}
res <- rbind(c(shape_rel, rate_rel),
             c(shape_nrm, rate_nrm),
             c(1, rate_cens))

rownames(res) <- c("Cens.", "Rel", "NRM")
colnames(res) <- c("Shape", "Rate")

# rates are on yearly scale
round(res, 3)

```


# Mstate analysis 


```{r}
# Check causespecific hazard of relapse with survival
cox_rel <- coxph(Surv(ci_allo1, delta == 1) ~ ,
                 data = dat_mds)

# Transition matrix 
tmat <- trans.comprisk(2, c("Rel", "NRM"))
tmat
```


