---
title: "Generating data and inducing missingness"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Generating data and inducing missingness}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.width = 7,
  fig.height = 6,
  fig.align = 'center',
  message = FALSE, 
  warning = FALSE
)
```


```{r setup}
library(SimsCauseSpecCovarMiss)
library(tidyverse)
library(ggpubr)

theme_set(theme_bw(base_size = 16) +
            theme(legend.position = "right",
                  plot.title = element_text(hjust = 0.5)))

set.seed(123)
```


# Generating data


```{r bin_dat}
dat_bin <- generate_dat(n = 1000,
                        X_type = "binary",
                        r = 0.5,
                        ev1_pars = list("a1" = 2, "h1_0" = 1,
                                        "b1" = 1, "gamm1" = 1),
                        ev2_pars = list("a2" = 2.5, "h2_0" = .5, 
                                        "b2" = .5, "gamm2" = .5),
                        rate_cens = 0.01)

head(dat_bin)
```



```{r plot_bin_dat, dev='svg'}
ggplot(dat_bin, aes(X, Z)) +
  geom_jitter(position = position_jitter(width = .1, height = 0),
              alpha = .5, col = 9)
```

# Inducing missingness 

Demo with continous data.

## MCAR

```{r dat_MCAR}
dat_MCAR <- generate_dat(n = 1000, # 1000
                         X_type = "contin",
                         r = 0.5,
                         ev1_pars = list("a1" = 2, "h1_0" = 1,
                                        "b1" = 1, "gamm1" = 1),
                         ev2_pars = list("a2" = 2.5, "h2_0" = .5, 
                                        "b2" = .5, "gamm2" = .5),
                         rate_cens = 1, 
                         mech = "MCAR",
                         p = 0.5)
```



```{r plot_MCAR, dev='svg'}
ggplot(dat_MCAR, aes(X_orig, Z, col = factor(miss_ind))) +
  geom_point() +
  scale_colour_manual("Missing indicator",
                      labels = c("Observed", "Missing"),
                      values = c(9, 6))
```

## MAR (depending on Z)


```{r dat_MAR}
dat_MAR <- generate_dat(n = 1000, # 1000
                        X_type = "contin",
                        r = 0.5,
                        ev1_pars = list("a1" = 2, "h1_0" = 1,
                                        "b1" = 1, "gamm1" = 1),
                        ev2_pars = list("a2" = 2.5, "h2_0" = .5, 
                                        "b2" = .5, "gamm2" = .5),
                        rate_cens = 1, 
                        mech = "MAR",
                        p = 0.5,
                        eta1 = -2)
                         
```


```{r plot_MAR, dev='svg'}
ggplot(dat_MAR, aes(X_orig, Z, col = factor(miss_ind))) +
  geom_point(alpha = .75) +
  scale_colour_manual("Missing indicator",
                      labels = c("Observed", "Missing"),
                      values = c(9, 6))
```


```{r grid_mar, echo=FALSE, dev='svg'}
etas <- c(-2, -1, -.5)

eta_plots_MAR <- lapply(etas, function(eta) {
  dat <- generate_dat(n = 1000, # 1000
               X_type = "contin",
               r = 0.5,
               ev1_pars = list("a1" = 2, "h1_0" = 1,
                                        "b1" = 1, "gamm1" = 1),
               ev2_pars = list("a2" = 2.5, "h2_0" = .5, 
                                        "b2" = .5, "gamm2" = .5),
               rate_cens = 1, 
               mech = "MAR",
               p = 0.5,
               eta1 = eta)
  
  ggplot(dat, aes(X_orig, Z, col = factor(miss_ind))) +
    geom_point(alpha = .75) +
    scale_colour_manual("Missing indicator",
                      labels = c("Observed", "Missing"),
                      values = c(9, 6)) +
    xlab("X") +
    ggtitle(bquote(eta[1] ~ "=" ~ .(eta))) 
})

ggarrange(plotlist = eta_plots_MAR, nrow = 1,
          common.legend = T, legend = "bottom")
```


## MNAR (values of X itself)



```{r dat_MNAR}
dat_MNAR <- generate_dat(n = 1000, # 1000
                         X_type = "contin",
                         r = 0.5,
                         ev1_pars = list("a1" = 2, "h1_0" = 1,
                                        "b1" = 1, "gamm1" = 1),
                         ev2_pars = list("a2" = 2.5, "h2_0" = .5, 
                                        "b2" = .5, "gamm2" = .5),
                         rate_cens = 1, 
                         mech = "MNAR",
                         p = 0.5,
                         eta1 = -2)
```



```{r plot_MNAR, echo=FALSE, dev='svg'}
eta_plots_MNAR <- lapply(etas, function(eta) {
  dat <- generate_dat(n = 1000, # 1000
                      X_type = "contin",
                      r = 0.5,
                      ev1_pars = list("a1" = 2, "h1_0" = 1,
                                        "b1" = 1, "gamm1" = 1),
                      ev2_pars = list("a2" = 2.5, "h2_0" = .5, 
                                        "b2" = .5, "gamm2" = .5),
                      rate_cens = 1, 
                      mech = "MNAR",
                      p = 0.5,
                      eta1 = -2)
                         
  
  ggplot(dat, aes(X_orig, Z, col = factor(miss_ind))) +
    geom_point(alpha = .75) +
    scale_colour_manual("Missing indicator",
                      labels = c("Observed", "Missing"),
                      values = c(9, 6)) +
    xlab("X") +
    ggtitle(bquote(eta[1] ~ "=" ~ .(eta))) 
})

ggarrange(plotlist = eta_plots_MNAR, nrow = 1,
          common.legend = T, legend = "bottom")
```


## MAR-GEN


```{r dat_MAR-GEN}
dat_MAR_GEN <- generate_dat(n = 1000,
                            X_type = "contin",
                            r = 0.5,
                            ev1_pars = list("a1" = 2, "h1_0" = 1,
                                        "b1" = 1, "gamm1" = 1),
                            ev2_pars = list("a2" = 2.5, "h2_0" = .5, 
                                        "b2" = .5, "gamm2" = .5),
                            rate_cens = 1, 
                            mech = "MAR_GEN",
                            p = 0.5,
                            eta1 = -2)
```




```{r plot_MAR-GEN, dev='svg'}

ggplot(dat_MAR_GEN, aes(t, X_orig, col = factor(miss_ind))) +
  geom_point() +
  #ylab("log(t)") +
  scale_colour_manual("Missing indicator",
                      labels = c("Observed", "Missing"),
                      values = c(9, 6)) +
  ylab("X")

# Add extra plot with effect on covariate?

```
